// @ts-check

/**
 * Manual sidebar.
 *
 * Previously this was a single autogenerated entry. It is now explicit so the
 * large Features section can be grouped into scannable sub-categories without
 * moving any files (URLs stay stable). Other sections list their pages directly.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'index',

    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started/first-app'],
    },

    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      link: {type: 'doc', id: 'features/overview'},
      items: [
        {
          type: 'category',
          label: 'Integrations & Services',
          items: [
            'features/auth',
            'features/notifications',
            'features/inapp-purchases-subscription',
            'features/credits-system',
            'features/admob-ads',
            'features/inapp-review',
            'features/ai-integration',
            'features/firebase-integration',
          ],
        },
        {
          type: 'category',
          label: 'App Building Blocks',
          items: [
            'features/local-storage',
            'features/user-preferences',
            'features/network',
            'features/ui-components',
            'features/screen-generator',
            'features/feature-flag',
            'features/permissions',
            'features/logging',
            'features/splash-screen',
          ],
        },
        {
          type: 'category',
          label: 'Build & Release',
          items: [
            'features/testing',
            'features/github-ci-cd',
            'features/scripts',
            'features/store-screenshots',
            'features/app-landing-page',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/domain',
        'architecture/data',
        'architecture/presentation',
        'architecture/navigation',
        'architecture/util',
        'architecture/di',
      ],
    },

    {
      type: 'category',
      label: 'Production',
      items: [
        'production/pre-publishing-checklist',
        'production/android',
        'production/iOS',
        'production/fastlane',
      ],
    },

    'file-locations',
  ],
};

export default sidebars;
